version: '2.1'
services:
  faucet:
    container_name: faucet
    build: ./
    ports:
      - 3001:3001
    environment:
      NODE_ENV: 'production'
     
networks:
  default:
    external:
      name: verify_service
